:description: This chapter gives an orientation on how to get started with Neo4j.
[[get-started-with-neo4j]]
= Get started with Neo4j

[abstract]
--
This chapter gives an orientation on how to get started with Neo4j.
--

== Installing Neo4j

The easiest way to set up an environment for developing an application with Neo4j and Cypher is to use Neo4j Desktop.
Download Neo4j Desktop from https://neo4j.com/download/ and follow the installation instructions for your operating system.


== Documentation guide

All the official documentation is available at https://neo4j.com/docs/.
That is where you find the full manuals such as:

* link:{neo4j-docs-base-uri}/cypher-manual/{neo4j-version}[The Cypher manual] -- This is the comprehensive manual for Cypher.
* link:{neo4j-docs-base-uri}/driver-manual/1.7/[The Driver manual] -- This manual describes the officially supported drivers for Neo4j.
* link:{neo4j-docs-base-uri}/operations-manual/{neo4j-version}/[The Operations manual] -- This manual describes how to deploy and maintain Neo4j.

The https://neo4j.com/docs/cypher-refcard/current[Cypher Refcard] is a valuable asset when learning and writing Cypher.

Additionally, you can find more specialized documentation along with API documentation and documentation for older Neo4j releases.
