:description: This section gives an orientation on how to get started with Neo4j.

[[get-started-with-neo4j]]
= Get started with Neo4j

There are a number of options how to install Neo4j and how to get started running Cypher queries.


== Installing Neo4j

The easiest way to set up an environment for developing an application with Neo4j and Cypher is to use Neo4j Desktop.
Download Neo4j Desktop from link:https://neo4j.com/download/[] and follow the installation instructions for your operating system.

[TIP]
====
For more options on how to get started with Neo4j and Cypher see link:https://neo4j.com/try-neo4j/[].
====


== Documentation

All the official documentation is available at link:https://neo4j.com/docs/[].

That is where you find the full manuals such as:

* xref:4.3@cypher-manual:ROOT:index.adoc#cypher-manual[The Cypher manual] -- This is the comprehensive manual for Cypher.
* xref:4.3@operations-manual:ROOT:index.adoc#operations-manual[The Operations manual] -- This manual describes how to deploy and maintain Neo4j.

The https://neo4j.com/docs/cypher-refcard/current[Cypher Refcard] is a valuable asset when learning and writing Cypher.

Additionally, you can find more specialized documentation along with API documentation and documentation for older Neo4j releases.
