= Get started with Neo4j
:page-layout: docs-ndl
:page-theme: docs
:page-role: explainer
:page-show-home-link: true
:page-hide-nav-title: true
// :page-disablefeedback: true
:page-toclevels: -1

[.display.cards.selectable]

== Explore the capabilities of graph databases

With a property graph database at its core, Neo4j offers an ecosystem of tools, applications, and libraries which aim to help you get started with the technology.

=== What is Neo4j

[.icon]
image:ROOT:icon-neo4j.svg[]

[.description]
Learn what is a graph database and how to use it in your projects.

[.link]
xref:whats-neo4j.adoc[]

=== What is a graph database

[.icon]
image:ROOT:icon-graph.svg[]

[.description]
Learn the principles of a graph database.

[.link]
xref:graph-database.adoc[]

=== What is Cypher

[.icon]
image:ROOT:icon-developer.svg[]

[.description]
Learn Cypher, Neo4j's graph query language, and start thinking about graphs and patterns.

[.link]
xref:cypher.adoc[]

=== Model your data to Neo4j

[.icon]
image:ROOT:icon-csvtodb.svg[]

[.description]
Discover strategies to model your data and to improve your workflow.

[.link]
link:{docs-home}/model[]

=== Import data to Neo4j

[.icon]
image:ROOT:icon-import.svg[]

[.description]
Read more about the several ways of importing data to your Neo4j graph database.

[.link]
link:{docs-home}/import/[]

=== Create applications with Neo4j

[.icon]
image:ROOT:icon-code.svg[]

[.description]
Run through detailed examples of how to integrate Neo4j with your preferred programming language. 

[.link]
link:{docs-home}/create-applications[]

=== Data science with Neo4j

[.icon]
image:ROOT:icon-gds.svg[]

[.description]
Learn how to use Neo4j Graph Data Science, a library of graph algorithms for analysts and data scientists.

[.link]
link:{docs-home}/gds[]

=== Visualize data in Neo4j

[.icon]
image:ROOT:icon-dataviz.svg[]

[.description]
Learn how to export your graph data in Neo4j for display as a visualization.

[.link]
link:{docs-home}/visualize/[]

[.next-steps]
== GraphAcademy courses

Here are some recommended interactive courses to get started with Neo4j:

. link:https://graphacademy.neo4j.com/courses/neo4j-fundamentals/[*Neo4j fundamentals*]
+
Enroll to this course on GraphAcademy to get started with the technology.

. link:https://graphacademy.neo4j.com/courses/cypher-fundamentals/[*Cypher fundamentals*]
+
Enroll to this 60-minute course to learn the essentials of using Cypher.

. link:https://graphacademy.neo4j.com/courses/modeling-fundamentals/[*Data modeling fundamentals*]
+
Learn how to design a Neo4j graph using best practices.

. link:https://graphacademy.neo4j.com/courses/importing-fundamentals/[*Importing data fundamentals*]
+
Learn how to import data into Neo4j.