= What is Neo4j?
:description: An introduction on how to get started with Neo4j.
:!page-layout:
include::https://raw.githubusercontent.com/neo4j-graphacademy/courses/main/asciidoc/ads/generic.adoc[]

[.center]
image::ROOT:neo4j-architecture.svg[]

Neo4j is a _native graph database_, which means that it implements a true <<graph>> model all the way down to the storage level.
Instead of using a "graph abstraction" on top of another technology, the data is stored in Neo4j in the same way you may whiteboard your ideas.

Since 2007, Neo4j has evolved into a rich ecosystem of tools, applications, and libraries. 
This ecosystem allows you to integrate graph technologies with your working environment in a number of ways which are here described.

== How to interact with Neo4j

Neo4j uses Cypher, a declarative query language similar to SQL, but optimized for graphs.
The same language is also used by other databases such as SAP HANA Graph and Redis graph via the http://www.opencypher.org/[openCypher project].

Another option is to use link:https://neo4j.com/docs/drivers-apis/[drivers].
Neo4j currently supports Java, JavaScript, .NET, Python, Go, GraphQL, Spring, and more.

Beyond the core graph, Neo4j also provides ACID transactions, <<cluster>> support, and runtime failover.

== Start exploring

Deploying a database is the first step to take to explore Neo4j.
link:{docs-home}/deployment-option[Choose a deployment method] that better suits your project among the following options:

=== Fully managed cloud service

link:https://neo4j.com/cloud/platform/aura-graph-database/[Neo4j AuraDB] is a fully managed cloud service that allows you to start exploring Neo4j right from your browser.

If you are a data scientist, you might also want to check link:https://neo4j.com/docs/aura/aurads/[Neo4j AuraDS] and get access to more than 65 pretuned link:https://neo4j.com/docs/graph-data-science/current/algorithms/[graph algorithms].

Neo4j Aura has both free and subscription-based editions.
link:https://neo4j.com/pricing/[See full comparison].

=== Self-managed cloud services

You can also deploy your graph database on a link:{docs-home}/operations-manual/current/cloud-deployments[cloud platform] of your choice.
Neo4j works with Amazon Web Services (AWS), Google Cloud (GCP), and Microsoft Azure. 

For this option, you need to link:{docs-home}/operations-manual/current/installation/[install Neo4j] to your machine or use link:{docs-home}/desktop-manual[Neo4j Desktop] in case your project is not in a production environment.

Neo4j is available for installation on link:https://neo4j.com/docs/operations-manual/current/installation/linux/[Linux], link:https://neo4j.com/docs/operations-manual/current/installation/osx/[macOs], and link:https://neo4j.com/docs/operations-manual/current/installation/windows/[Windows].

=== Self-managed local deployment

If you prefer to work with a local deployment, you can follow the same instructions: install link:{docs-home}/desktop-manual[Neo4j Desktop] in case you are not working in a production environment or link:{docs-home}/operations-manual/current/installation/[install Neo4j] to your machine.

==== Neo4j on Docker

link:{docs-home}/operations-manual/current/docker[Docker] can be downloaded for macOS, Windows, and Linux from the link:https://www.docker.com/get-started[DockerHub].
It hosts an official Neo4j image that provides a standard, ready-to-run package of Neo4j Community Edition and Enterprise Edition for a variety of versions.

==== Neo4j on Kubernetes

With Neo4j Helm charts, you can deploy both a standalone and a cluster deployment of link:{docs-home}/operations-manual/current/kubernetes[Neo4j on Kubernetes], and use configuration options suitable for the most common scenarios. 

[NOTE]
Neo4j has free and subscription-based licensing options.
Read more about the link:https://neo4j.com/licensing/[available editions].

== Work with data

You can link:{docs-home}/import[import] your own data to Neo4j or use link:{docs-home}/getting-started/appendix/example-data/[example datasets].
Both Aura and Neo4j Desktop feature embedded guides that allow you to create example datasets and start link:{docs-home}/getting-started/cypher-intro/[querying your database].

In case you are working with your own dataset, it is recommended to link:{docs-home}/getting-started/data-modeling/[model your data] for a better experience with your new graph database.

== Keep learning

To learn more about xref:graph-database.adoc[what is a graph database] and xref:graphdb-concepts.adoc[the concepts] behind the technology, continue reading the documentation or check xref:resources.adoc[other curated resources].

Neo4j is written in Java and Scala.
You can check the source code on https://github.com/neo4j/neo4j[GitHub^].

ifndef::backend-pdf[]
[discrete.glossary]
endif::[]
== Glossary

include::glossary.adoc[]

ifdef::backend-pdf[]
<<<
endif::[]