[[examples-hello-world-sample-chapter]]
Hello world Sample Chapter
==========================

This is a sample documentation test, demonstrating different ways of
bringing code and other artifacts into Asciidoc form. The title of the
generated document is determined from the method name, replacing "+_+" with
" ".

Below you see a number of different ways to generate text from source,
inserting it into the JavaDoc documentation (really being Asciidoc markup)
via the snippet markers (see below) and programmatic adding with runtime data
in the Java code.

- The annotated graph as http://www.graphviz.org/[GraphViz]-generated visualization:

.Hello World Graph
include::includes/hello-world-sample-chapter-graph.adoc[]

- A sample Cypher query:

include::includes/hello-world-sample-chapter-cypher.adoc[]

- A sample text output snippet:

include::includes/hello-world-sample-chapter-output.adoc[]

- a generated source link to the original GIThub source for this test:

include::includes/hello-world-sample-chapter-github.adoc[]

- The full source for this example as a source snippet, highlighted as Java code:

include::includes/hello-world-sample-chapter-sampleDocumentation.adoc[]

This is the end of this chapter.


