[[examples-uniqueness-of-paths-in-traversals]]
Uniqueness of Paths in traversals
=================================

This example is demonstrating the use of node uniqueness.
Below an imaginary domain graph with Principals that own pets that are descendant to other pets.

.Descendants example graph
include::includes/uniqueness-of-paths-in-traversals-graph.adoc[]

In order to return all descendants of `Pet0` which have the relation `owns` to `Principal1` (`Pet1` and `Pet3`),
the Uniqueness of the traversal needs to be set to `NODE_PATH` rather than the default `NODE_GLOBAL`.
This way nodes can be traversed more that once, and paths that have different nodes but can have some nodes in common (like the start and end node) can be returned.

include::includes/uniqueness-of-paths-in-traversals-traverser.adoc[]

This will return the following paths:

include::includes/uniqueness-of-paths-in-traversals-output.adoc[]

In the default `path.toString()` implementation, `(1)--[knows,2]-->(4)` denotes
a node with ID=1 having a relationship with ID=2 or type `knows` to a node with ID=4.

Let's create a new `TraversalDescription` from the old one,
having `NODE_GLOBAL` uniqueness to see the difference.

[TIP]
--
The `TraversalDescription` object is immutable, so we have to use the new instance returned with the new uniqueness setting.
--

include::includes/uniqueness-of-paths-in-traversals-traverseNodeGlobal.adoc[]

Now only one path is returned:

include::includes/uniqueness-of-paths-in-traversals-outNodeGlobal.adoc[]


