= Neo4j Getting Started Guide
:neo4j-docs-base-uri: https://neo4j.com/docs

This repository contains the AsciiDoc and other sources to build the link:{neo4j-docs-base-uri}/getting-started[Neo4j Getting Started Guide].

== Installation

To build these docs locally you will need link:https://nodejs.org/en/download/package-manager/[Node & NPM^] installed.

To install the dependencies run:

[source,sh]
npm install


== Live Preview

To preview the docs, run:

[source,sh]
npm run start

This will build a set of HTML files in `build/site` and then serve them through an express server at http://localhost:8000.
The start script will also listen for changes and automatically rebuild the files automatically.
You'll still need to refresh the page to view the changes.

== Contributing

To make changes to this repository, please create a fork of this repo and a new branch to stage your changes. Your branch should be prefixed with the version number, for example `4.3-new-examples`.

When you are finished with your changes push the branch to your fork and create a Pull Request. Please add at least one approver.