= Neo4j Getting Started Guide
:docs-uri: https://neo4j.com/docs

This repository contains the AsciiDoc and other sources to build the link:{docs-uri}/getting-started[Neo4j Getting Started Guide].

== Installation

To build these docs locally you will need link:https://nodejs.org/en/download/package-manager/[Node & NPM^] installed.

To install the dependencies run:

[source,sh]
npm install


== Live Preview

To preview the docs, run:

[source,sh]
npm run start

This command builds a set of HTML files in `build/site` and then serve them through an express server at http://localhost:8000.
The start script will also listen for changes and automatically rebuild the files automatically.
You'll still need to refresh the page to view the changes.

== Contributing

To make changes to this repository, please create a fork of this repo and a new branch to stage your changes.

=== Branch management

The docs-getting-started repo contains the following branches:

* `dev` - this branch is published on the staging server, as a preview, but we will never publish from this branch publicly.
* `main` - this is the currently published version, and therefore is the branch that we publish the GSG from.
PRs merged into this branch will be published live immediately.
* Other (versioned) branches -- `3.5`, `4.0`, `4.4`, `5.x`, etc. -- are not maintained any longer.

=== Raising Pull Requests

* Always raise Pull Requests against the `dev` branch.
* Please add at least one approver.
* When merging a Pull Request, always use the "Squash and Merge" option.
* After a Pull Request has been merged, you can publish the changes immediately by cherry-picking the PR to the `main` branch. 
