= Neo4j - OGM Object Graph Mapper
:aura_signup: https://neo4j.com/cloud/aura/?ref=developer-guides
:testcontainers-version: 1.17.6
:tags: ogm, object-graph-map, app-development, applications
:description: For Java developers that require a mechanism to manage their domain objects with Neo4j, this guide introduces the Neo4j Object Graph Mapping (OGM) library.

[abstract]
{description}
[abstract]
You should be familiar with xref:appendix/graphdb-concepts/index.adoc[graph database concepts] and the property graph model.
You should have link:{aura_signup}[created an Neo4j AuraDB cloud instance], or link:/download/[installed Neo4j locally]


[#neo4j-ogm]
== Neo4j-OGM

include::https://raw.githubusercontent.com/neo4j/neo4j-ogm/master/neo4j-ogm-docs/src/main/asciidoc/introduction/index.adoc[lines=25..32,leveloffset=+1]

[#ogm-features]
== Features

The Neo4j-OGM supports the features you would expect:

* Object graph mapping of annotated node- and relationship-entities
* Neo4jSession for direct interaction with Neo4j
* Fast class metadata scanning
* Optimized management of data loading and change tracking for minimal data transfers
* Multiple transports: binary (bolt), HTTP and embedded
* Persistence lifecycle events
* Query result projection to DTOs

[#ogm-code-example]
== Minimal Code Snippet

This code example is taken from the Example Project (see below).

[source,java]
----
@NodeEntity
public class Movie {

   @Id @GeneratedValue
   Long id;

   @Property(name="title")
   private String name;
}

@NodeEntity
public class Actor {

   @Id @GeneratedValue
   private Long id;

   @Property(name="name")
   private String fullName;

   @Relationship(type="ACTED_IN", direction=Relationship.OUTGOING)
   private List<Role> filmography;

}

@RelationshipEntity(type="ACTED_IN")
@Id @GeneratedValue
    private Long relationshipId;
	@Property
    private String title;
    
	@StartNode
    private Actor actor;
    
	@EndNode
    private Movie movie;
}
----

=== The Example Project

The Neo4j example project is a small, one page webapp for the movies database built into the Neo4j tutorial.
The front-end page is the same for all drivers: movie search, movie details, and a graph visualization of actors and movies.
Each backend implementation shows you how to connect to Neo4j from each of the different languages and drivers.

You can learn more about our small, consistent example project across many different language drivers link:/developer/example-project[here^].
You will find the implementations for all drivers as https://github.com/neo4j-examples?q=movies[individual GitHub repositories^], which you can clone and deploy directly.

[#ogm-faq]
== FAQ

include::https://raw.githubusercontent.com/neo4j/neo4j-ogm/master/neo4j-ogm-docs/src/main/asciidoc/appendix/faq.adoc[lines=3..-1,leveloffset=+1]

[#ogm-resources]
== Resources

:maven-ogm: http://search.maven.org/#search|ga|1|a%3A%22neo4j-ogm%22

[cols="1,4"]
|===
| icon:user[] Authors | The Neo4j and http://graphaware.com/neo4j-experts/[GraphAware Teams]
| icon:gift[] Package | link:{maven-ogm}[http://maven.org]
| icon:github[] Source | https://github.com/neo4j/neo4j-ogm
| icon:book[] Docs | https://neo4j.com/docs/ogm-manual/current/
|===

include::https://raw.githubusercontent.com/neo4j/neo4j-ogm/master/README.adoc[lines=1]
:ogm-version: {version}
include::https://raw.githubusercontent.com/neo4j/neo4j-ogm/master/neo4j-ogm-docs/src/main/asciidoc/reference/getting-started.adoc[lines=3..-1,leveloffset=+1]
