[[data-modeling]]
= What is graph data modeling?
:description: graph-modeling, data-model, schema, create-model, translate-model, model-performance, model-example
:page-ad-overline-link: https://graphacademy.neo4j.com/courses/modeling-fundamentals/?ref=docs
:page-ad-overline: Neo4j GraphAcademy
:page-ad-title: Graph Data Modeling Fundamentals
:page-ad-description: Learn how to design a Neo4j graph using best practices
:page-ad-link: https://graphacademy.neo4j.com/courses/modeling-fundamentals/?ref=docs
:page-ad-underline-role: button
:page-ad-underline: Learn more

Data modeling is a practice that defines the logic of queries and the structure of the data in storage.
It is an important step to take when using any type of database, as it helps ensuring data integrity and improved performance.

== How to create a graph data model

There are different ways to organize data into a <<data model>>, but most likely that will depend on what questions you want to answer.

Consider an example case in which you work for a retail company that wants to learn what products customers buy first and what products they buy subsequently.
To answer that, you need to:

. Have data on the products sold by the company, who are its customers, and what they purchased at a certain point in time.
This process is known as "entity extraction".
. Understand how these entities relate to each other, and what the properties for these entities are (e.g. time of purchase, customer name).
. Optionally, you can use xref:data-modeling/data-modeling-tools.adoc[no-code data modeling tools] to visualize the model before actually creating it.
. If satisfied, you can start writing the data into an instance.

In this fictional scenario, you can start by adding this information to the graph:

[source,cypher]
--
MERGE (c:Customer {name: "John"})
MERGE (p:Product {name: “Camera”})
MERGE (c)-[:BUYS]->(p)
--

Then, you can test this model by querying the database with a question (e.g. who bought a camera):

[source,cypher]
--
MATCH (c)-[b:BUYS]->(p:Product {name:"Camera"})
RETURN c
--

Keep in mind that graph data modeling is an iterative process.
Your initial graph data model is only a starting point, but as you learn more about the use cases or if the use cases change, the initial graph data model will need to adapt. 
In addition, you may find that especially when the graph scales, you will need to modify the graph (xref:data-modeling/graph-model-refactoring.adoc[refactor]) to achieve the best performance for your key use cases.

More generally, you can summarize the process of creating a data model in these steps:

. Understand the domain and define specific use cases (questions) for the application.
. Develop the initial graph data model by extracting entities and how they relate to each other.
. Test the use cases against the initial data model.
. Create the graph with test data using Cypher.
. Test the use cases, including performance against the graph.
. Refactor (improve) the graph data model due to a change in the key use cases or for performance reasons.
. Implement the refactoring on the graph and retest using Cypher.

== Keep learning

For a more hands-on approach to data modeling, try the following resources:

// * xref:tutorials/tutorial-data-modeling.adoc[Tutorial: Create a graph data model]: a more in-depth tutorial that follows up to the example used here.
* link:https://graphacademy.neo4j.com/courses/modeling-fundamentals/?ref=docs[GraphAcademy: Data Modeling Fundamentals]: enroll to an interactive course.
* xref:data-modeling/relational-to-graph-modeling.adoc[From relational to graph]: learn how to adapt data from a relational to a graph data model.
* xref:data-modeling/data-modeling-tools.adoc[Data modeling tools]: see a list of tools you can use to create your data model.
* xref:data-modeling/modeling-tips.adoc[Data modeling tips]: check tips on how to improve your data modeling skills.
* xref:data-modeling/modeling-designs.adoc[Modeling designs]: see examples of data modeling designs that can be used as strategy for your project.
* link:https://neo4j.com/graphgists/[Neo4j GraphGists]: find examples of graph data modeling shared by the Neo4j community.

ifndef::backend-pdf[]
[discrete.glossary]
endif::[]
== Glossary

include::../glossary.adoc[]

ifdef::backend-pdf[]
<<<
endif::[]