[[administration-security-writes]]
= Write privileges

[abstract]
--
This section explains how to use Cypher to manage write privileges on graphs.
--


* <<administration-security-writes-create, The `CREATE` privilege>>
* <<administration-security-writes-delete, The `DELETE` privilege>>
* <<administration-security-writes-set-label, The `SET LABEL` privilege>>
* <<administration-security-writes-remove-label, The `REMOVE LABEL` privilege>>
* <<administration-security-writes-set-property, The `SET PROPERTY` privilege>>
* <<administration-security-writes-merge, The `MERGE` privilege>>
* <<administration-security-writes-write, The `WRITE` privilege>>
* <<administration-security-writes-all, The `ALL GRAPH PRIVILEGES` privilege>>



Write privileges are defined for different parts of the graph:

* `CREATE` - allows creating nodes and relationships.
* `DELETE` - allows deleting nodes and relationships.
* `SET LABEL` - allows setting the specified node labels using the `SET` clause.
* `REMOVE LABEL` - allows removing the specified node labels using the `REMOVE` clause.
* `SET PROPERTY` - allows setting properties on nodes and relationships.

There are also compound privileges which combine the above specific privileges:

* `MERGE` - allows match, create and set property to permit the `MERGE` command.
* `WRITE` - allows all write operations on an entire graph.
* `ALL GRAPH PRIVILEGES` - allows all read and write operation on an entire graph.


[role=enterprise-edition]
[[administration-security-writes-create]]
== The `CREATE` privilege

The `CREATE` privilege allows a user to create new node and relationship elements in a graph.
See the Cypher <<query-create, CREATE>> clause.

include::grant-create-syntax.adoc[]

For example, granting the ability to create elements on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT CREATE ON GRAPH neo4j ELEMENTS * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT CREATE ON GRAPH neo4j ELEMENTS * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The `CREATE` privilege can also be denied.

include::deny-create-syntax.adoc[]

For example, denying the ability to create nodes with the label `foo` on all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY CREATE ON GRAPH * NODES foo TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY CREATE ON GRAPH * NODES foo TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
If the user attempts to create nodes with a label that does not already exist in the database, then the user must also possess the
<<administration-security-administration-database-tokens, CREATE NEW LABEL>> privilege. The same applies to new relationships - the
<<administration-security-administration-database-tokens, CREATE NEW RELATIONSHIP TYPE>> privilege is required.


====

[role=enterprise-edition]
[[administration-security-writes-delete]]
== The `DELETE` privilege

The `DELETE` privilege allows a user to delete node and relationship elements in a graph.
See the Cypher <<query-delete, DELETE>> clause.

include::grant-delete-syntax.adoc[]

For example, granting the ability to delete elements on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT DELETE ON GRAPH neo4j ELEMENTS * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT DELETE ON GRAPH neo4j ELEMENTS * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The `DELETE` privilege can also be denied.

include::deny-delete-syntax.adoc[]

For example, denying the ability to delete relationships with the relationship type `bar` on all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY DELETE ON GRAPH * RELATIONSHIPS bar TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY DELETE ON GRAPH * RELATIONSHIPS bar TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Users with `DELETE` privilege, but restricted `TRAVERSE` privileges, will not be able to do `DETACH DELETE` in all cases.
 See <<operations-manual#detach-delete-restricted-user, Operations Manual -> Fine-grained access control>> for more info.


====

[role=enterprise-edition]
[[administration-security-writes-set-label]]
== The `SET LABEL` privilege

The `SET LABEL` privilege allows you to set labels on a node using the <<set-set-a-label-on-a-node, SET clause>>.

include::grant-set-label-syntax.adoc[]

For example, granting the ability to set any label on nodes of the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT SET LABEL * ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT SET LABEL * ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Unlike many of the other read and write privileges, it is not possible to restrict the `SET LABEL` privilege to specific ELEMENTS, NODES or RELATIONSHIPS.


====

The `SET LABEL` privilege can also be denied.

include::deny-set-label-syntax.adoc[]

For example, denying the ability to set the label `foo` on nodes of all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY SET LABEL foo ON GRAPH * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY SET LABEL foo ON GRAPH * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
If no instances of this label exist in the database, then the <<administration-security-administration-database-tokens, CREATE NEW LABEL>> privilege is also required.


====

[role=enterprise-edition]
[[administration-security-writes-remove-label]]
== The `REMOVE LABEL` privilege

The `REMOVE LABEL` privilege allows you to remove labels from a node using the <<remove-remove-a-label-from-a-node, REMOVE clause>>.

include::grant-remove-label-syntax.adoc[]

For example, granting the ability to remove any label from nodes of the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT REMOVE LABEL * ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT REMOVE LABEL * ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Unlike many of the other read and write privileges, it is not possible to restrict the `REMOVE LABEL` privilege to specific ELEMENTS, NODES or RELATIONSHIPS.


====

The `REMOVE LABEL` privilege can also be denied.

include::deny-remove-label-syntax.adoc[]

For example, denying the ability to remove the label `foo` from nodes of all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY REMOVE LABEL foo ON GRAPH * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY REMOVE LABEL foo ON GRAPH * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[role=enterprise-edition]
[[administration-security-writes-set-property]]
== The `SET PROPERTY` privilege

The `SET PROPERTY` privilege allows a user to set a property on a node or relationship element in a graph using the <<set-set-a-property, SET clause>>.

include::grant-set-property-syntax.adoc[]

For example, granting the ability to set any property on all elements of the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT SET PROPERTY {*} ON HOME GRAPH ELEMENTS * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT SET PROPERTY {*} ON HOME GRAPH ELEMENTS * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The `SET PROPERTY` privilege can also be denied.

include::deny-set-property-syntax.adoc[]

For example, denying the ability to set the property `foo` on nodes with the label `bar` on all graphs to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY SET PROPERTY { foo } ON GRAPH * NODES bar TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY SET PROPERTY { foo } ON GRAPH * NODES bar TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
If the users attempts to set a property with a property name that does not already exist in the database the user must also possess the
<<administration-security-administration-database-tokens, CREATE NEW PROPERTY NAME>> privilege.


====

[role=enterprise-edition]
[[administration-security-writes-merge]]
== The `MERGE` privilege

The `MERGE` privilege is a compound privilege that combines `TRAVERSE` and `READ` (i.e. `MATCH`) with `CREATE` and `SET PROPERTY`. This is intended to
 permit use of <<query-merge, the MERGE command>> but is applicable to all reads and writes that require these privileges.

include::grant-merge-syntax.adoc[]

For example, granting `MERGE` on all elements of the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT MERGE {*} ON GRAPH neo4j ELEMENTS * TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT MERGE {*} ON GRAPH neo4j ELEMENTS * TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

It is not possible to deny the `MERGE` privilege. If it is desirable to prevent a users from creating elements and setting properties, use
<<administration-security-writes-create, DENY CREATE>> or <<administration-security-writes-set-property,DENY SET PROPERTY>>.

[NOTE]
====
If the users attempts to create nodes with a label that does not already exist in the database the user must also possess the
<<administration-security-administration-database-tokens, CREATE NEW LABEL>> privilege. The same applies to new relationships and properties - the
<<administration-security-administration-database-tokens, CREATE NEW RELATIONSHIP TYPE>> or
<<administration-security-administration-database-tokens, CREATE NEW PROPERTY NAME>> privileges are required.


====

[role=enterprise-edition]
[[administration-security-writes-write]]
== The `WRITE` privilege

The `WRITE` privilege allows the user to execute any write command on a graph.

include::grant-write-syntax.adoc[]

For example, granting the ability to write on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT WRITE ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT WRITE ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Unlike the more specific write commands, it is not possible to restrict `WRITE` privileges to specific ELEMENTS, NODES or RELATIONSHIPS.
If it is desirable to prevent a user from writing to a subset of database objects, a `GRANT WRITE` can be combined with more specific
`DENY` commands to target these elements.


====

The `WRITE` privilege can also be denied.

include::deny-write-syntax.adoc[]

For example, denying the ability to write on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY WRITE ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY WRITE ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====
Users with `WRITE` privilege but restricted `TRAVERSE` privileges will not be able to do `DETACH DELETE` in all cases.
 See <<operations-manual#detach-delete-restricted-user, Operations Manual -> Fine-grained access control>> for more info.


====

[role=enterprise-edition]
[[administration-security-writes-all]]
== `ALL GRAPH PRIVILEGES`

The `ALL GRAPH PRIVILEGES` privilege allows the user to execute any command on a graph.

include::grant-all-graph-privileges-syntax.adoc[]

For example, granting all graph privileges on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
GRANT ALL GRAPH PRIVILEGES ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
GRANT ALL GRAPH PRIVILEGES ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[NOTE]
====

Unlike the more specific read and write commands, it is not possible to restrict `ALL GRAPH PRIVILEGES` privileges to specific ELEMENTS,
NODES or RELATIONSHIPS. If it is desirable to prevent a user from reading or writing to a subset of database objects,
a `GRANT ALL GRAPH PRIVILEGES` can be combined with more specific `DENY` commands to target these elements.


====

The `ALL GRAPH PRIVILEGES` privilege can also be denied.

include::deny-all-graph-privileges-syntax.adoc[]

For example, denying all graph privileges on the graph `neo4j` to the role `regularUsers` would be achieved using:


.Query
[source, cypher]
----
DENY ALL GRAPH PRIVILEGES ON GRAPH neo4j TO regularUsers
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
CREATE USER jake SET PASSWORD 'abc123' CHANGE NOT REQUIRED SET STATUS ACTIVE
CREATE ROLE regularUsers
GRANT ROLE regularUsers TO jake
GRANT ACCESS ON DATABASE neo4j TO regularUsers

]]></database><command><![CDATA[
DENY ALL GRAPH PRIVILEGES ON GRAPH neo4j TO regularUsers
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

