[[administration-built-in-roles]]
= Built-in roles

[abstract]
--
This section explains the default privileges of the built-in roles in Neo4j and how to recreate them if needed.
--

All of the commands described in this chapter require that the user executing the commands has the rights to do so.
The privileges listed in the following sections are the default set of privileges for each built-in role:



* <<administration-built-in-roles-public, The `PUBLIC` role>>
* <<administration-built-in-roles-reader, The `reader` role>>
* <<administration-built-in-roles-editor, The `editor` role>>
* <<administration-built-in-roles-publisher, The `publisher` role>>
* <<administration-built-in-roles-architect, The `architect` role>>
* <<administration-built-in-roles-admin, The `admin` role>>


[role=enterprise-edition]
[[administration-built-in-roles-public]]
== The `PUBLIC` role

All users are granted the `PUBLIC` role, and it can not be revoked or dropped. By default, it gives access to the default database and allows executing all procedures and user defined functions.

[[administration-built-in-roles-public-privileges]]
=== Privileges of the `PUBLIC` role


.Query
[source, cypher]
----
SHOW ROLE PUBLIC PRIVILEGES AS COMMANDS
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +command+
| +"GRANT ACCESS ON HOME DATABASE TO `PUBLIC`"+
| +"GRANT EXECUTE FUNCTION * ON DBMS TO `PUBLIC`"+
| +"GRANT EXECUTE PROCEDURE * ON DBMS TO `PUBLIC`"+
1+d|Rows: 3
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW ROLE PUBLIC PRIVILEGES AS COMMANDS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[administration-built-in-roles-public-recreate]]
=== How to recreate the `PUBLIC` role

The `PUBLIC` role can not be dropped and thus there is no need to recreate the role itself.
To restore the role to its original capabilities, two steps are needed. First, all `GRANT` or `DENY` privileges on this role should be revoked (see output of `SHOW ROLE PUBLIC PRIVILEGES AS REVOKE COMMANDS` on what to revoke).
Secondly, the following queries must be run:


.Query
[source, cypher]
----
GRANT ACCESS ON HOME DATABASE TO PUBLIC
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT ACCESS ON HOME DATABASE TO PUBLIC
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT EXECUTE PROCEDURES * ON DBMS TO PUBLIC
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT EXECUTE PROCEDURES * ON DBMS TO PUBLIC
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT EXECUTE USER DEFINED FUNCTIONS * ON DBMS TO PUBLIC
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT EXECUTE USER DEFINED FUNCTIONS * ON DBMS TO PUBLIC
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The resulting `PUBLIC` role now has the same privileges as the original built-in `PUBLIC` role.

[role=enterprise-edition]
[[administration-built-in-roles-reader]]
== The `reader` role

The `reader` role can perform read-only queries on all graphs except for the `system` database.

[[administration-built-in-roles-reader-privileges]]
=== Privileges of the `reader` role


.Query
[source, cypher]
----
SHOW ROLE reader PRIVILEGES AS COMMANDS
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +command+
| +"GRANT ACCESS ON DATABASE * TO `reader`"+
| +"GRANT MATCH {*} ON GRAPH * NODE * TO `reader`"+
| +"GRANT MATCH {*} ON GRAPH * RELATIONSHIP * TO `reader`"+
1+d|Rows: 3
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW ROLE reader PRIVILEGES AS COMMANDS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[administration-built-in-roles-reader-recreate]]
=== How to recreate the `reader` role


To restore the role to its original capabilities two steps are needed. First, if not already done, execute `DROP ROLE reader`.
Secondly, the following queries must be run:


.Query
[source, cypher]
----
CREATE ROLE reader
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
CREATE ROLE reader
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT ACCESS ON DATABASE * TO reader
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT ACCESS ON DATABASE * TO reader
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT MATCH {*} ON GRAPH * TO reader
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT MATCH {*} ON GRAPH * TO reader
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The resulting `reader` role now has the same privileges as the original built-in `reader` role.

[role=enterprise-edition]
[[administration-built-in-roles-editor]]
== The `editor` role

The `editor` role can perform read and write operations on all graphs except for the `system` database, but can not make new labels, property keys or relationship types.

[[administration-built-in-roles-editor-privileges]]
=== Privileges of the `editor` role


.Query
[source, cypher]
----
SHOW ROLE editor PRIVILEGES AS COMMANDS
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +command+
| +"GRANT ACCESS ON DATABASE * TO `editor`"+
| +"GRANT MATCH {*} ON GRAPH * NODE * TO `editor`"+
| +"GRANT MATCH {*} ON GRAPH * RELATIONSHIP * TO `editor`"+
| +"GRANT WRITE ON GRAPH * TO `editor`"+
1+d|Rows: 4
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW ROLE editor PRIVILEGES AS COMMANDS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[administration-built-in-roles-editor-recreate]]
=== How to recreate the `editor` role


To restore the role to its original capabilities two steps are needed. First, if not already done, execute `DROP ROLE editor`.
Secondly, the following queries must be run:


.Query
[source, cypher]
----
CREATE ROLE editor
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
CREATE ROLE editor
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT ACCESS ON DATABASE * TO editor
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT ACCESS ON DATABASE * TO editor
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT MATCH {*} ON GRAPH * TO editor
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT MATCH {*} ON GRAPH * TO editor
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT WRITE ON GRAPH * TO editor
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT WRITE ON GRAPH * TO editor
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The resulting `editor` role now has the same privileges as the original built-in `editor` role.

[role=enterprise-edition]
[[administration-built-in-roles-publisher]]
== The `publisher` role

The `publisher` role can do the same as <<administration-built-in-roles-editor,`editor`>>, but can also create new labels, property keys and relationship types.

[[administration-built-in-roles-publisher-privileges]]
=== Privileges of the `publisher` role


.Query
[source, cypher]
----
SHOW ROLE publisher PRIVILEGES AS COMMANDS
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +command+
| +"GRANT ACCESS ON DATABASE * TO `publisher`"+
| +"GRANT MATCH {*} ON GRAPH * NODE * TO `publisher`"+
| +"GRANT MATCH {*} ON GRAPH * RELATIONSHIP * TO `publisher`"+
| +"GRANT NAME MANAGEMENT ON DATABASE * TO `publisher`"+
| +"GRANT WRITE ON GRAPH * TO `publisher`"+
1+d|Rows: 5
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW ROLE publisher PRIVILEGES AS COMMANDS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[administration-built-in-roles-publisher-recreate]]
=== How to recreate the `publisher` role


To restore the role to its original capabilities two steps are needed. First, if not already done, execute `DROP ROLE publisher`.
Secondly, the following queries must be run:


.Query
[source, cypher]
----
CREATE ROLE publisher
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
CREATE ROLE publisher
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT ACCESS ON DATABASE * TO publisher
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT ACCESS ON DATABASE * TO publisher
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT MATCH {*} ON GRAPH * TO publisher
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT MATCH {*} ON GRAPH * TO publisher
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT WRITE ON GRAPH * TO publisher
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT WRITE ON GRAPH * TO publisher
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT NAME MANAGEMENT ON DATABASE * TO publisher
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT NAME MANAGEMENT ON DATABASE * TO publisher
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The resulting `publisher` role now has the same privileges as the original built-in `publisher` role.

[role=enterprise-edition]
[[administration-built-in-roles-architect]]
== The `architect` role

The `architect` role can do the same as the <<administration-built-in-roles-publisher,`publisher`>>, as well as create and manage indexes and constraints.

[[administration-built-in-roles-architect-privileges]]
=== Privileges of the `architect` role


.Query
[source, cypher]
----
SHOW ROLE architect PRIVILEGES AS COMMANDS
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +command+
| +"GRANT ACCESS ON DATABASE * TO `architect`"+
| +"GRANT CONSTRAINT MANAGEMENT ON DATABASE * TO `architect`"+
| +"GRANT INDEX MANAGEMENT ON DATABASE * TO `architect`"+
| +"GRANT MATCH {*} ON GRAPH * NODE * TO `architect`"+
| +"GRANT MATCH {*} ON GRAPH * RELATIONSHIP * TO `architect`"+
| +"GRANT NAME MANAGEMENT ON DATABASE * TO `architect`"+
| +"GRANT WRITE ON GRAPH * TO `architect`"+
1+d|Rows: 7
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW ROLE architect PRIVILEGES AS COMMANDS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[administration-built-in-roles-architect-recreate]]
=== How to recreate the `architect` role


To restore the role to its original capabilities two steps are needed. First, if not already done, execute `DROP ROLE architect`.
Secondly, the following queries must be run:


.Query
[source, cypher]
----
CREATE ROLE architect
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
CREATE ROLE architect
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT ACCESS ON DATABASE * TO architect
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT ACCESS ON DATABASE * TO architect
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT MATCH {*} ON GRAPH * TO architect
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT MATCH {*} ON GRAPH * TO architect
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT WRITE ON GRAPH * TO architect
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT WRITE ON GRAPH * TO architect
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT NAME MANAGEMENT ON DATABASE * TO architect
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT NAME MANAGEMENT ON DATABASE * TO architect
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT INDEX MANAGEMENT ON DATABASE * TO architect
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT INDEX MANAGEMENT ON DATABASE * TO architect
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT CONSTRAINT MANAGEMENT ON DATABASE * TO architect
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT CONSTRAINT MANAGEMENT ON DATABASE * TO architect
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The resulting `architect` role now has the same privileges as the original built-in `architect` role.

[role=enterprise-edition]
[[administration-built-in-roles-admin]]
== The `admin` role

The `admin` role can do the same as the <<administration-built-in-roles-architect,`architect`>>, as well as manage databases, users, roles and privileges.

[[administration-built-in-roles-admin-privileges]]
=== Privileges of the `admin` role


.Query
[source, cypher]
----
SHOW ROLE admin PRIVILEGES AS COMMANDS
----

.Result
[role="queryresult",options="header,footer",cols="1*<m"]
|===
| +command+
| +"GRANT ACCESS ON DATABASE * TO `admin`"+
| +"GRANT ALL DBMS PRIVILEGES ON DBMS TO `admin`"+
| +"GRANT CONSTRAINT MANAGEMENT ON DATABASE * TO `admin`"+
| +"GRANT INDEX MANAGEMENT ON DATABASE * TO `admin`"+
| +"GRANT MATCH {*} ON GRAPH * NODE * TO `admin`"+
| +"GRANT MATCH {*} ON GRAPH * RELATIONSHIP * TO `admin`"+
| +"GRANT NAME MANAGEMENT ON DATABASE * TO `admin`"+
| +"GRANT START ON DATABASE * TO `admin`"+
| +"GRANT STOP ON DATABASE * TO `admin`"+
| +"GRANT TRANSACTION MANAGEMENT (*) ON DATABASE * TO `admin`"+
| +"GRANT WRITE ON GRAPH * TO `admin`"+
1+d|Rows: 11
|===

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
SHOW ROLE admin PRIVILEGES AS COMMANDS
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

[[administration-built-in-roles-admin-recreate]]
=== How to recreate the `admin` role


To restore the role to its original capabilities two steps are needed. First, if not already done, execute `DROP ROLE admin`.
Secondly, the following queries must be run in order to set up the privileges:


.Query
[source, cypher]
----
CREATE ROLE admin
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
CREATE ROLE admin
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT ALL DBMS PRIVILEGES ON DBMS TO admin
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT ALL DBMS PRIVILEGES ON DBMS TO admin
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT TRANSACTION MANAGEMENT ON DATABASE * TO admin
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT TRANSACTION MANAGEMENT ON DATABASE * TO admin
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT START ON DATABASE * TO admin
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT START ON DATABASE * TO admin
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT STOP ON DATABASE * TO admin
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT STOP ON DATABASE * TO admin
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT MATCH {*} ON GRAPH * TO admin
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT MATCH {*} ON GRAPH * TO admin
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT WRITE ON GRAPH * TO admin
----

[role="statsonlyqueryresult"]
0 rows, System updates: 2

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT WRITE ON GRAPH * TO admin
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]


.Query
[source, cypher]
----
GRANT ALL ON DATABASE * TO admin
----

[role="statsonlyqueryresult"]
0 rows, System updates: 1

ifndef::nonhtmloutput[]
[subs="none"]
++++
<formalpara role="cypherconsole">
<title>Try this query live</title>
<para><database><![CDATA[
none
]]></database><command><![CDATA[
GRANT ALL ON DATABASE * TO admin
]]></command></para></formalpara>
++++
endif::nonhtmloutput[]

The resulting `admin` role now has the same privileges as the original built-in `admin` role.

Additional information about restoring the admin role can be found in the <<operations-manual#recover-admin-role, Operations Manual -> Recover the admin role>>.

