[[csv-import]]
= Tutorial: Import CSV data using `LOAD CSV`
:description: This tutorial shows how to use the command LOAD CSV to import small to medium datasets in CSV format into Neo4j using Aura and on-premise deployments.
:page-pagination:

Neo4j supports xref:data-import/index.adoc#_methods_comparison[different methods] of importing CSV files, each catering for specific needs such as dataset size, link:{docs-home}/deployment-method[deployment method], and familiarity with Cypher.
This tutorial shows how to import CSV data into Neo4j using link:https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`] command.

[TIP]
====
For a more interactive experience, enroll to the GraphAcademy course link:https://graphacademy.neo4j.com/courses/importing-cypher/[Importing CSV data into Neo4j].
To import larger CSV files into Neo4j, see link:https://www.neo4j.com/docs/operations-manual/current/import/#import-tool-full[`neo4j-admin database import full`] and link:https://www.neo4j.com/docs/operations-manual/current/import/#import-tool-incremental[`neo4j-admin database import incremental`].
====

== Loading the file

Before loading the file, you need to first create an link:https://neo4j.com/product/auradb/[Aura instance] or choose a link:{docs-home}/deployment-options[deployment of your choice].
Then, you can load the file using `LOAD CSV` using the following command:

[source,cypher]
--
LOAD CSV [WITH HEADERS] FROM url [AS alias] [FIELDTERMINATOR char]
--

In this tutorial, you will use a link to load the CSV file:

[source,cypher]
--
LOAD CSV WITH HEADERS 
FROM 'https://data.neo4j.com/importing-cypher/people.csv' AS row
RETURN row
--

This is the content of the example `people.csv` file:

[source,csv]
--
personId,name,birthYear
23945,Gerard Pires,1942
553509,Helen Reddy,1941
113934,Susan Flannery,1939
--

Note that the `FIELDTERMINATOR` wasn’t specified in the `LOAD CSV` clause because the default value is a comma. 
If the field terminator was a pipe character, then you would need to include the field terminator, for example:

[source,cypher]
--
LOAD CSV WITH HEADERS
FROM 'https://data.neo4j.com/importing-cypher/people.csv'
as row FIELDTERMINATOR '|'
RETURN row
--

== Check the imported data

Here is a to-do list that will help you check the imported data:

. Count the number of rows in the CSV file and compare it to the number of rows returned by the `LOAD CSV` clause by using the link:https://neo4j.com/docs/cypher-manual/current/subqueries/count/[`COUNT`] function in a new query:
+
[source,cypher]
--
LOAD CSV WITH HEADERS
FROM 'https://data.neo4j.com/importing-cypher/people.csv'
as row
RETURN count(row)
--
+

. Make sure header names match those in the CSV file.

. Search for typos in the data and in the queries.

== Model your data

Before you import data into Neo4j, there is no structure, only the dataset itself.
As you import data, however, you create the graph data model.

Refer to the xref:data-modeling/index.adoc[Data modeling section] or follow the xref:data-modeling/tutorial-data-modeling.adoc[Tutorial: Create a graph data model] to learn more.
