[[query-plan-eager]]
== Eager ==
For isolation purposes, the `Eager` operator ensures that operations affecting subsequent operations are executed fully for the whole dataset before continuing execution.
 Information from the stores is fetched in a lazy manner; i.e. the pattern matching might not be fully exhausted before updates are applied.
 To guarantee reasonable semantics, the query planner will insert `Eager` operators into the query plan to prevent updates from influencing pattern matching;
 this scenario is exemplified by the query below, where the `DELETE` clause influences the `MATCH` clause.
 The `Eager` operator can cause high memory usage when importing data or migrating graph structures.
 In such cases, the operations should be split into simpler steps; e.g. importing nodes and relationships separately.
 Alternatively, the records to be updated can be returned, followed by an update statement.

.Query
include::includes/query-plan-eager.query.adoc[]



.Query Plan
[source]
----
Compiler CYPHER 4.3

Planner COST

Runtime PIPELINED

Runtime version 4.3

+-----------------+------------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| Operator        | Details          | Estimated Rows | Rows | DB Hits | Memory (Bytes) | Page Cache Hits/Misses | Time (ms) | Other               |
+-----------------+------------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| +ProduceResults |                  |             36 |    0 |       0 |                |                        |           | Fused in Pipeline 3 |
| |               +------------------+----------------+------+---------+----------------+                        |           +---------------------+
| +EmptyResult    |                  |             36 |    0 |       0 |                |                        |           | Fused in Pipeline 3 |
| |               +------------------+----------------+------+---------+----------------+                        |           +---------------------+
| +Apply          |                  |             36 |  504 |       0 |                |                        |           |                     |
| |\              +------------------+----------------+------+---------+----------------+                        |           +---------------------+
| | +Merge        | CREATE (anon_37) |             36 |  504 |       0 |                |                        |           | Fused in Pipeline 3 |
| | |             +------------------+----------------+------+---------+----------------+                        |           +---------------------+
| | +AllNodesScan | anon_37          |           1260 |  504 |     540 |           1216 |                    0/0 |     1.396 | Fused in Pipeline 3 |
| |               +------------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| +Eager          |                  |             36 |   36 |       0 |            944 |                    0/0 |     0.086 | In Pipeline 2       |
| |               +------------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| +Delete         | b                |             36 |   36 |       9 |                |                        |           | Fused in Pipeline 1 |
| |               +------------------+----------------+------+---------+----------------+                        |           +---------------------+
| +Delete         | a                |             36 |   36 |      12 |                |                        |           | Fused in Pipeline 1 |
| |               +------------------+----------------+------+---------+----------------+                        |           +---------------------+
| +Delete         | r                |             36 |   36 |      18 |                |                        |           | Fused in Pipeline 1 |
| |               +------------------+----------------+------+---------+----------------+                        |           +---------------------+
| +Eager          |                  |             36 |   36 |       0 |            944 |                   19/0 |     1.862 | Fused in Pipeline 1 |
| |               +------------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+
| +Expand(All)    | (a)-[r]-(b)      |             36 |   36 |      36 |                |                        |           | Fused in Pipeline 0 |
| |               +------------------+----------------+------+---------+----------------+                        |           +---------------------+
| +AllNodesScan   | a                |             35 |   35 |      36 |             72 |                    2/0 |     0.293 | Fused in Pipeline 0 |
+-----------------+------------------+----------------+------+---------+----------------+------------------------+-----------+---------------------+

Total database accesses: 651, total allocated memory: 1344

----
