[[language-guides]]
= Connecting to Neo4j
:aura_signup: https://neo4j.com/cloud/aura/?ref=developer-guides
:tags: programming-languages, applications, bolt, app-development
:page-ad-overline-link: https://neo4j.com/cloud/aura/?ref=developer-guides
:page-ad-overline: Neo4j Aura
:page-ad-title: Don't have a Neo4j instance? Launch one now.
:page-ad-description: Free forever, no credit card required.
:page-ad-link: https://neo4j.com/cloud/aura/?ref=developer-guides
:page-ad-underline-role: button
:page-ad-underline: Start on AuraDB


[#neo4j-app-dev]
== Neo4j language guides

This section is designed to provide detailed examples of how to integrate Neo4j with your preferred programming language.
Neo4j *officially supports the drivers for .Net, Java, JavaScript, Go, and Python* for the binary Bolt protocol.

Our community contributors provide drivers for all major programming languages for all protocols and APIs.
In this section, we provide an introduction and a consistent example application for several languages and Neo4j drivers.

You should be familiar with xref:appendix/graphdb-concepts/index.adoc[graph database concepts] and the property graph model.
You should have link:{aura_signup}[created an Neo4j AuraDB cloud instance], or link:/download/[installed Neo4j locally].

[#graphacademy]
== Learn with GraphAcademy

We have a range of link:https://graphacademy.neo4j.com/categories/developer/?ref=guides[Neo4j Developer courses^] that teach you to build connect to Neo4j using each of our officially supported Drivers.

link:https://graphacademy.neo4j.com/courses/app-java/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-java/badge/[Building Neo4j Applications with Java, width=120]^]
link:https://graphacademy.neo4j.com/courses/app-nodejs/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-nodejs/badge/[Building Neo4j Applications with Node.js, width=120]^]
link:https://graphacademy.neo4j.com/courses/app-python/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-python/badge/[Building Neo4j Applications with Python, width=120]^]
link:https://graphacademy.neo4j.com/courses/app-dotnet/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-dotnet/badge/[Building Neo4j Applications with .NET, width=120]^]
link:https://graphacademy.neo4j.com/courses/app-go/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-go/badge/[Building Neo4j Applications with Go, width=120]^]

[#connect-neo4j]
== How to connect to Neo4j?

If you've created an link:{aura_signup}[AuraDB instance^], or link:/download/[installed] and started Neo4j as a server on your system, you can already work interactively with the database via the built-in Neo4j Browser, which you find in the AuraDB console, or if you're running locally, on http://localhost:7474[localhost:7474].

To build an application, you want to connect to Neo4j from your technology stack, use a driver which connects to Neo4j via Bolt or HTTP.

[#bolt-protocol]
== The binary Bolt Protocol

Starting with Neo4j v3.0, we support a binary protocol called link:https://neo4j.com/docs/bolt/current/[Bolt].
It is based on the PackStream serialization and supports the Cypher type system, protocol versioning, authentication, and TLS via certificates.
For Neo4j Clusters, Bolt provides smart client routing with load balancing and failover.

The binary protocol is enabled in Neo4j by default, so you can use any language driver that supports it.

_For more details on the protocol implementation, see the https://github.com/neo4j-contrib/boltkit[implementers documentation^]._

[#neo4j-drivers]
== Neo4j Drivers

Neo4j provides official drivers for a number of popular programming languages.
Below you can find links to their reference documentation:

* link:https://neo4j.com/docs/java-manual/current/[Java]
* link:https://neo4j.com/docs/dotnet-manual/current/[.NET]
* link:https://neo4j.com/docs/javascript-manual/current/[JavaScript]
* link:https://neo4j.com/docs/python-manual/current/[Python]
* link:https://neo4j.com/docs/go-manual/current/[Go]
* link:https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/[Spring]

[NOTE]
====
Always use the latest version of the driver, as it will always work both with the previous Neo4j long-term support release and with the current and next major releases.
The latest 5.x driver supports connection to any Neo4j 5 and 4.4 instance, and will also be compatible with Neo4j 6.
====

To demonstrate connection to and usage of Neo4j in different programming languages, an example application is created.
It is a http://my-neo4j-movies-app.herokuapp.com/[simple, one-page webapp^], that uses Neo4j's Movie demo database (movie, actor, director) as a dataset.
The same front-end web page in all applications consumes three REST endpoints provided by backend implemented in the different programming languages and drivers:

* movie search by title
* single movie listing
* graph visualization of the domain model


[#app-project-source]
== GitHub

The source code for all the different language examples is available on https://github.com/neo4j-examples?query=movies[GitHub^] as individual repositories that can be cloned and directly used as starting points.


[#http-api]
== Using the HTTP API

[NOTE]
====
The HTTP API is available in Community Edition and Enterprise Edition, but not in AuraDB.
====


If you want to access Neo4j programmatically, you can also use the HTTP API which enables you to:

* POST one or more Cypher statements with parameters.
* Keep transactions open over multiple requests.
* Choose different result formats.

Let's look at one of the underlying remote API endpoint that Neo4j offers to run queries.
These APIs can be then used directly via a HTTP library or a driver for your language.

A simple HTTP Cypher request, executable in the Neo4j Browser, would look like this:

[source, json]
----
:POST /db/<database-name>/tx/commit {"statements":[
      {"statement":"CREATE (p:Person {firstName: $name}) RETURN p",
       "parameters":{"name":"Daniel"}}
    ]}
----

Some of the language drivers use the HTTP API under the hood, but make them available in a more convenient way.

[.ad]
== link:https://graphacademy.neo4j.com/[Learn with GraphAcademy^]

Learn everything you need to know to build an application on top of Neo4j with free, hands-on courses from link:https://graphacademy.neo4j.com/[Neo4j GraphAcademy^].

link:https://graphacademy.neo4j.com/?ref=guides[Learn more^,role=button]
link:https://graphacademy.neo4j.com/categories/?ref=guides[or view courses by category^]
