= Using Neo4j from JavaScript
:aura_signup: https://neo4j.com/cloud/aura/?ref=developer-guides
:programming-language: javascript
:category: drivers
:tags: javascript, official-driver, app-development, applications
:description: If you are a JavaScript developer, this guide provides an overview of options for connecting to Neo4j.
// :page-ad-overline-link: https://graphacademy.neo4j.com/
// :page-ad-overline: Neo4j GraphAcademy
// :page-ad-title: Building Neo4j Applications with Node.js
// :page-ad-description: Learn how to interact with Neo4j from your Node.js app using the Neo4j Python Driver
// :page-ad-link: https://graphacademy.neo4j.com/courses/app-nodejs/
// :page-ad-underline: Learn more

[abstract]
This guide introduces the Neo4j JavaScript driver and links to the relevant resources.

You should be familiar with xref:appendix/graphdb-concepts/index.adoc[graph database concepts] and the property graph model.
You should have link:{aura_signup}[created an Neo4j AuraDB cloud instance], or link:/download/[installed Neo4j locally].

[#neo4j-javascript]
== Neo4j for JavaScript developers

Neo4j provides libraries that allow you to connect to the database and develop applications
which create, read, update, and delete information from the graph.

The Neo4j JavaScript driver connects to the database using the binary protocol Bolt.
It aims to be minimal while being idiomatic to JavaScript, allowing you to subscribe to a stream of responses, errors, and completion events.

For detailed information on how to build applications with Neo4j and JavaScript, go to the link:https://neo4j.com/docs/javascript-manual/current/[Neo4j JavaScript Driver Manual^].
There you can find instructions and code examples for every workflow step.


[#driver-configuration]
=== Driver configuration

From Neo4j **4.0** and onwards, the default encryption setting is *off* by default and Neo4j will no longer generate self-signed certificates.
This applies to default installations, installations through Neo4j Desktop and Docker images.
You can https://neo4j.com/docs/migration-guide/current/upgrade-driver/#_configure_ssl_policy_for_bolt_server_and_https_server[verify the encryption level of your server^] by checking the `dbms.connector.bolt.enabled` key in `neo4j.conf`.

// tag::table[]
.Table Scheme Usage
|===
| Certificate Type | Neo4j Cluster | Neo4j Standalone Server  | Direct Connection to Cluster Member

| *Unencrypted*
| `neo4j`
| `neo4j`
| `bolt`

| *Encrypted with Full Certificate*
| `neo4j+s`
| `neo4j+s`
| `bolt+s`


| *Encrypted with Self-Signed Certificate*
| `neo4j+ssc`
| `neo4j+ssc`
| `bolt+ssc`

| *https://neo4j.com/aura/[Neo4j AuraDB^]*
| `neo4j+s`
| N/A
| N/A

|===


Review your https://neo4j.com/docs/operations-manual/current/security/ssl-framework/[SSL Framework settings^] when going into production.
// end::table[]

[cols="3*"]
|===
| Name
| icon:tag[] Version
| icon:user[] Authors

| neo4j-driver
| {javascript-driver-version}
| The Neo4j Team

| https://www.npmjs.com/package/neo4j-driver[icon:gift[] Package]
|
| https://community.neo4j.com/c/drivers-stacks/javascript[Neo4j Online Community^]

| https://neo4j.com/docs/javascript-manual/current/[icon:book[] Docs^]
| link:/docs/api/javascript-driver/current/[icon:code[] API]
| http://github.com/neo4j/neo4j-javascript-driver[icon:github[] Source]
|===

=== The example project

The Neo4j example project is a small, one page webapp for the movies database built into the Neo4j tutorial.
The front-end page is the same for all drivers: movie search, movie details, and a graph visualization of actors and movies.
Each backend implementation shows you how to connect to Neo4j from each of the different languages and drivers.

You can learn more about our small, consistent example project across many different language drivers link:/developer/example-project[here^].
You will find the implementations for all drivers as https://github.com/neo4j-examples?q=movies[individual GitHub repositories^], which you can clone and deploy directly.


[#js-http-endpoint]
== Using the HTTP endpoint directly

You can use Neo4j HTTP API to send Cypher queries to and receive responses from Neo4j.

The endpoint protocol and formats are explained in detail in the link:https://neo4j.com/docs/http-api/current/[Neo4j HTTP API Manual^].

It enables you do to much more, for example sending many statements per request or keeping transactions open across multiple requests.


== link:https://graphacademy.neo4j.com/?ref=guides[Learn with GraphAcademy^]

image::https://graphacademy.neo4j.com/courses/app-nodejs/badge/[width=100, float=left]

=== link:https://graphacademy.neo4j.com/courses/app-nodejs/?ref=guides[Building Neo4j Applications with Node.js^]

In this free course, we walk through the steps to integrate Neo4j into your Node.js projects.
You will learn about the Neo4j JavaScript driver, how sessions and transactions work and how to query Neo4j from an existing application.


